hosts:
  shomosumi-work:
    hostname: conoha2-deployer
    remote_user: deployer
    deploy_path: ~/workspace/excel2json-app
    branch: master
    writable_mode: chmod
    env:
      environment: production
    labels:
      env: prod
