name: deploy production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy production -vvv
          private-key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          ssh-config: |
            Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
            Host conoha2-deployer
              User deployer
              Port 22
              HostName 157.7.214.70


#      - name: Install SSH key
#        uses: shimataro/ssh-key-action@v1.6.1
#        with:
#          name: -id_rsa-conoha2deployer
#          private-key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
#          config: ${{ secrets.DEPLOYER_CONFIG }} # ssh target だけで接続できるように設定
#          known_hosts: ${{ secrets.DEPLOYER_KNOWN_HOSTS }}
#          if_key_exists: replace
#
##      - name: Adding Known Hosts
##        run: ssh-keyscan -H ${{ secrets.DEPLOYER_SSH_HOST }} >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts && chmod 0600 ~/.ssh/id_rsa-conoha2deployer && chmod 0600 ~/.ssh/config
#
#      - name: Connect SSH
#        run: ssh conoha2-deployer echo "test"
#
#      - name: Deploy to production
#        run: vendor/bin/dep deploy production -vvv
#        env:
#          DEPLOYER_SSH_USER: deployer

