name: Unit Test

on:
  - pull_request

jobs:
  unittest:
    - name: PhpUnit for Laravel
    # You may pin to the exact commit or the version.
    # uses: svikramjeet/git-action-laravel-phpunit@4bad6262594f6a8b7c7b7be49f2e5191fc3f50f1
    uses: svikramjeet/git-action-laravel-phpunit@v1.0
